### ISSUE TITLE
Consider turning on branch protection for the main branch of this repo

### ISSUE THREAD

**Issue by mmaraya** [uibcdf/action-sphinx-docs-to-gh-pages#7]
Turning on protection for the main branch could significantly reduce the risk of intentional malicious code injection. More context in https://github.com/ossf/scorecard/blob/main/docs/checks.md#branch-protection. GitHub documentation in https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches.

**Comment by dprada** [comment]
Thanks for the suggestion @mmaraya!
I'm going to do it now. 👍🏻
